/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Accessories
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Accessories', ['BaseModel', AccessoriesModel]);

    function AccessoriesModel(BaseModel) {
        var Accessories = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.accessory = this.getValue(obj.accessory);
        };

        Accessories.prototype = new BaseModel();
        Accessories.prototype.constructor = Accessories;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Accessories.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'accessory', realName: 'Accessory', array: true, type: 'Accessory' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Accessories.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        Accessories.prototype.getAccessory = function () {
            return this.accessory;
        };
    
        /**
         * Setter for Accessory
         * 
         * @param {array} value 
         */
        Accessories.prototype.setAccessory = function (value) {
            this.accessory = value;
        };
    
        return Accessories;
    }

}(angular));
