/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AlternateVersion
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('AlternateVersion', ['BaseModel', AlternateVersionModel]);

    function AlternateVersionModel(BaseModel) {
        var AlternateVersion = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.aSIN = this.getValue(obj.aSIN);
            this.title = this.getValue(obj.title);
            this.binding = this.getValue(obj.binding);
        };

        AlternateVersion.prototype = new BaseModel();
        AlternateVersion.prototype.constructor = AlternateVersion;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        AlternateVersion.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'aSIN', realName: 'ASIN' },
                { name: 'title', realName: 'Title' },
                { name: 'binding', realName: 'Binding' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        AlternateVersion.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        AlternateVersion.prototype.getASIN = function () {
            return this.aSIN;
        };
    
        /**
         * Setter for ASIN
         * 
         * @param {string} value 
         */
        AlternateVersion.prototype.setASIN = function (value) {
            this.aSIN = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        AlternateVersion.prototype.getTitle = function () {
            return this.title;
        };
    
        /**
         * Setter for Title
         * 
         * @param {string|null} value 
         */
        AlternateVersion.prototype.setTitle = function (value) {
            this.title = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        AlternateVersion.prototype.getBinding = function () {
            return this.binding;
        };
    
        /**
         * Setter for Binding
         * 
         * @param {string|null} value 
         */
        AlternateVersion.prototype.setBinding = function (value) {
            this.binding = value;
        };
    
        return AlternateVersion;
    }

}(angular));
