/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AlternateVersions
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('AlternateVersions', ['BaseModel', AlternateVersionsModel]);

    function AlternateVersionsModel(BaseModel) {
        var AlternateVersions = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.alternateVersion = this.getValue(obj.alternateVersion);
        };

        AlternateVersions.prototype = new BaseModel();
        AlternateVersions.prototype.constructor = AlternateVersions;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        AlternateVersions.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'alternateVersion', realName: 'AlternateVersion', array: true, type: 'AlternateVersion' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        AlternateVersions.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        AlternateVersions.prototype.getAlternateVersion = function () {
            return this.alternateVersion;
        };
    
        /**
         * Setter for AlternateVersion
         * 
         * @param {array|null} value 
         */
        AlternateVersions.prototype.setAlternateVersion = function (value) {
            this.alternateVersion = value;
        };
    
        return AlternateVersions;
    }

}(angular));
