/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Arguments
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Arguments', ['BaseModel', ArgumentsModel]);

    function ArgumentsModel(BaseModel) {
        var Arguments = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.argument = this.getValue(obj.argument);
        };

        Arguments.prototype = new BaseModel();
        Arguments.prototype.constructor = Arguments;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Arguments.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'argument', realName: 'Argument', array: true, type: 'Argument' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Arguments.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        Arguments.prototype.getArgument = function () {
            return this.argument;
        };
    
        /**
         * Setter for Argument
         * 
         * @param {array} value 
         */
        Arguments.prototype.setArgument = function (value) {
            this.argument = value;
        };
    
        return Arguments;
    }

}(angular));
