/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BrowseNodes
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('BrowseNodes', ['BaseModel', BrowseNodesModel]);

    function BrowseNodesModel(BaseModel) {
        var BrowseNodes = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.request = this.getValue(obj.request);
            this.browseNode = this.getValue(obj.browseNode);
        };

        BrowseNodes.prototype = new BaseModel();
        BrowseNodes.prototype.constructor = BrowseNodes;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        BrowseNodes.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'request', realName: 'Request', type: 'Request' },
                { name: 'browseNode', realName: 'BrowseNode', array: true, type: 'BrowseNode' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        BrowseNodes.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Request|null}
         */
        BrowseNodes.prototype.getRequest = function () {
            return this.request;
        };
    
        /**
         * Setter for Request
         * 
         * @param {Request|null} value 
         */
        BrowseNodes.prototype.setRequest = function (value) {
            this.request = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        BrowseNodes.prototype.getBrowseNode = function () {
            return this.browseNode;
        };
    
        /**
         * Setter for BrowseNode
         * 
         * @param {array|null} value 
         */
        BrowseNodes.prototype.setBrowseNode = function (value) {
            this.browseNode = value;
        };
    
        return BrowseNodes;
    }

}(angular));
