/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BrowseNodeLookupRequestMsg
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('BrowseNodeLookupRequestMsg', ['BaseModel', BrowseNodeLookupRequestMsgModel]);

    function BrowseNodeLookupRequestMsgModel(BaseModel) {
        var BrowseNodeLookupRequestMsg = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.body = this.getValue(obj.body);
        };

        BrowseNodeLookupRequestMsg.prototype = new BaseModel();
        BrowseNodeLookupRequestMsg.prototype.constructor = BrowseNodeLookupRequestMsg;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        BrowseNodeLookupRequestMsg.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'body', realName: 'body', type: 'BrowseNodeLookup' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        BrowseNodeLookupRequestMsg.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {BrowseNodeLookup}
         */
        BrowseNodeLookupRequestMsg.prototype.getBody = function () {
            return this.body;
        };
    
        /**
         * Setter for Body
         * 
         * @param {BrowseNodeLookup} value 
         */
        BrowseNodeLookupRequestMsg.prototype.setBody = function (value) {
            this.body = value;
        };
    
        return BrowseNodeLookupRequestMsg;
    }

}(angular));
