/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BrowseNodeLookupResponse
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('BrowseNodeLookupResponse', ['BaseModel', BrowseNodeLookupResponseModel]);

    function BrowseNodeLookupResponseModel(BaseModel) {
        var BrowseNodeLookupResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.operationRequest = this.getValue(obj.operationRequest);
            this.browseNodes = this.getValue(obj.browseNodes);
        };

        BrowseNodeLookupResponse.prototype = new BaseModel();
        BrowseNodeLookupResponse.prototype.constructor = BrowseNodeLookupResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        BrowseNodeLookupResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'operationRequest', realName: 'OperationRequest', type: 'OperationRequest' },
                { name: 'browseNodes', realName: 'BrowseNodes', array: true, type: 'BrowseNodes' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        BrowseNodeLookupResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {OperationRequest|null}
         */
        BrowseNodeLookupResponse.prototype.getOperationRequest = function () {
            return this.operationRequest;
        };
    
        /**
         * Setter for OperationRequest
         * 
         * @param {OperationRequest|null} value 
         */
        BrowseNodeLookupResponse.prototype.setOperationRequest = function (value) {
            this.operationRequest = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        BrowseNodeLookupResponse.prototype.getBrowseNodes = function () {
            return this.browseNodes;
        };
    
        /**
         * Setter for BrowseNodes
         * 
         * @param {array|null} value 
         */
        BrowseNodeLookupResponse.prototype.setBrowseNodes = function (value) {
            this.browseNodes = value;
        };
    
        return BrowseNodeLookupResponse;
    }

}(angular));
