/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CartCreateRequestMsg
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CartCreateRequestMsg', ['BaseModel', CartCreateRequestMsgModel]);

    function CartCreateRequestMsgModel(BaseModel) {
        var CartCreateRequestMsg = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.body = this.getValue(obj.body);
        };

        CartCreateRequestMsg.prototype = new BaseModel();
        CartCreateRequestMsg.prototype.constructor = CartCreateRequestMsg;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CartCreateRequestMsg.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'body', realName: 'body', type: 'CartCreate' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CartCreateRequestMsg.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {CartCreate}
         */
        CartCreateRequestMsg.prototype.getBody = function () {
            return this.body;
        };
    
        /**
         * Setter for Body
         * 
         * @param {CartCreate} value 
         */
        CartCreateRequestMsg.prototype.setBody = function (value) {
            this.body = value;
        };
    
        return CartCreateRequestMsg;
    }

}(angular));
