/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CartCreateRequest
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CartCreateRequest', ['BaseModel', CartCreateRequestModel]);

    function CartCreateRequestModel(BaseModel) {
        var CartCreateRequest = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.mergeCart = this.getValue(obj.mergeCart);
            this.items = this.getValue(obj.items);
            this.responseGroup = this.getValue(obj.responseGroup);
        };

        CartCreateRequest.prototype = new BaseModel();
        CartCreateRequest.prototype.constructor = CartCreateRequest;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CartCreateRequest.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'mergeCart', realName: 'MergeCart' },
                { name: 'items', realName: 'Items', type: 'Items24' },
                { name: 'responseGroup', realName: 'ResponseGroup', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CartCreateRequest.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CartCreateRequest.prototype.getMergeCart = function () {
            return this.mergeCart;
        };
    
        /**
         * Setter for MergeCart
         * 
         * @param {string|null} value 
         */
        CartCreateRequest.prototype.setMergeCart = function (value) {
            this.mergeCart = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Items24|null}
         */
        CartCreateRequest.prototype.getItems = function () {
            return this.items;
        };
    
        /**
         * Setter for Items
         * 
         * @param {Items24|null} value 
         */
        CartCreateRequest.prototype.setItems = function (value) {
            this.items = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        CartCreateRequest.prototype.getResponseGroup = function () {
            return this.responseGroup;
        };
    
        /**
         * Setter for ResponseGroup
         * 
         * @param {array|null} value 
         */
        CartCreateRequest.prototype.setResponseGroup = function (value) {
            this.responseGroup = value;
        };
    
        return CartCreateRequest;
    }

}(angular));
