/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CartClearRequest
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CartClearRequest', ['BaseModel', CartClearRequestModel]);

    function CartClearRequestModel(BaseModel) {
        var CartClearRequest = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.cartId = this.getValue(obj.cartId);
            this.hMAC = this.getValue(obj.hMAC);
            this.mergeCart = this.getValue(obj.mergeCart);
            this.responseGroup = this.getValue(obj.responseGroup);
        };

        CartClearRequest.prototype = new BaseModel();
        CartClearRequest.prototype.constructor = CartClearRequest;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CartClearRequest.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'cartId', realName: 'CartId' },
                { name: 'hMAC', realName: 'HMAC' },
                { name: 'mergeCart', realName: 'MergeCart' },
                { name: 'responseGroup', realName: 'ResponseGroup', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CartClearRequest.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CartClearRequest.prototype.getCartId = function () {
            return this.cartId;
        };
    
        /**
         * Setter for CartId
         * 
         * @param {string|null} value 
         */
        CartClearRequest.prototype.setCartId = function (value) {
            this.cartId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CartClearRequest.prototype.getHMAC = function () {
            return this.hMAC;
        };
    
        /**
         * Setter for HMAC
         * 
         * @param {string|null} value 
         */
        CartClearRequest.prototype.setHMAC = function (value) {
            this.hMAC = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CartClearRequest.prototype.getMergeCart = function () {
            return this.mergeCart;
        };
    
        /**
         * Setter for MergeCart
         * 
         * @param {string|null} value 
         */
        CartClearRequest.prototype.setMergeCart = function (value) {
            this.mergeCart = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        CartClearRequest.prototype.getResponseGroup = function () {
            return this.responseGroup;
        };
    
        /**
         * Setter for ResponseGroup
         * 
         * @param {array|null} value 
         */
        CartClearRequest.prototype.setResponseGroup = function (value) {
            this.responseGroup = value;
        };
    
        return CartClearRequest;
    }

}(angular));
