/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CatalogNumberList
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CatalogNumberList', ['BaseModel', CatalogNumberListModel]);

    function CatalogNumberListModel(BaseModel) {
        var CatalogNumberList = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.catalogNumberListElement = this.getValue(obj.catalogNumberListElement);
        };

        CatalogNumberList.prototype = new BaseModel();
        CatalogNumberList.prototype.constructor = CatalogNumberList;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CatalogNumberList.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'catalogNumberListElement', realName: 'CatalogNumberListElement', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CatalogNumberList.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        CatalogNumberList.prototype.getCatalogNumberListElement = function () {
            return this.catalogNumberListElement;
        };
    
        /**
         * Setter for CatalogNumberListElement
         * 
         * @param {array|null} value 
         */
        CatalogNumberList.prototype.setCatalogNumberListElement = function (value) {
            this.catalogNumberListElement = value;
        };
    
        return CatalogNumberList;
    }

}(angular));
