/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Children
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Children', ['BaseModel', ChildrenModel]);

    function ChildrenModel(BaseModel) {
        var Children = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.browseNode = this.getValue(obj.browseNode);
        };

        Children.prototype = new BaseModel();
        Children.prototype.constructor = Children;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Children.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'browseNode', realName: 'BrowseNode', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Children.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        Children.prototype.getBrowseNode = function () {
            return this.browseNode;
        };
    
        /**
         * Setter for BrowseNode
         * 
         * @param {array} value 
         */
        Children.prototype.setBrowseNode = function (value) {
            this.browseNode = value;
        };
    
        return Children;
    }

}(angular));
