/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CollectionParent
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CollectionParent', ['BaseModel', CollectionParentModel]);

    function CollectionParentModel(BaseModel) {
        var CollectionParent = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.aSIN = this.getValue(obj.aSIN);
            this.title = this.getValue(obj.title);
        };

        CollectionParent.prototype = new BaseModel();
        CollectionParent.prototype.constructor = CollectionParent;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CollectionParent.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'aSIN', realName: 'ASIN' },
                { name: 'title', realName: 'Title' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CollectionParent.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CollectionParent.prototype.getASIN = function () {
            return this.aSIN;
        };
    
        /**
         * Setter for ASIN
         * 
         * @param {string|null} value 
         */
        CollectionParent.prototype.setASIN = function (value) {
            this.aSIN = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CollectionParent.prototype.getTitle = function () {
            return this.title;
        };
    
        /**
         * Setter for Title
         * 
         * @param {string|null} value 
         */
        CollectionParent.prototype.setTitle = function (value) {
            this.title = value;
        };
    
        return CollectionParent;
    }

}(angular));
