/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CorrectedQuery
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CorrectedQuery', ['BaseModel', CorrectedQueryModel]);

    function CorrectedQueryModel(BaseModel) {
        var CorrectedQuery = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.keywords = this.getValue(obj.keywords);
            this.message = this.getValue(obj.message);
        };

        CorrectedQuery.prototype = new BaseModel();
        CorrectedQuery.prototype.constructor = CorrectedQuery;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CorrectedQuery.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'keywords', realName: 'Keywords' },
                { name: 'message', realName: 'Message' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CorrectedQuery.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CorrectedQuery.prototype.getKeywords = function () {
            return this.keywords;
        };
    
        /**
         * Setter for Keywords
         * 
         * @param {string|null} value 
         */
        CorrectedQuery.prototype.setKeywords = function (value) {
            this.keywords = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CorrectedQuery.prototype.getMessage = function () {
            return this.message;
        };
    
        /**
         * Setter for Message
         * 
         * @param {string|null} value 
         */
        CorrectedQuery.prototype.setMessage = function (value) {
            this.message = value;
        };
    
        return CorrectedQuery;
    }

}(angular));
