/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Creator
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Creator', ['BaseModel', CreatorModel]);

    function CreatorModel(BaseModel) {
        var Creator = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.role = this.getValue(obj.role);
        };

        Creator.prototype = new BaseModel();
        Creator.prototype.constructor = Creator;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Creator.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'role', realName: 'Role' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Creator.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Creator.prototype.getRole = function () {
            return this.role;
        };
    
        /**
         * Setter for Role
         * 
         * @param {string} value 
         */
        Creator.prototype.setRole = function (value) {
            this.role = value;
        };
    
        return Creator;
    }

}(angular));
