/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CustomerReviews
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CustomerReviews', ['BaseModel', CustomerReviewsModel]);

    function CustomerReviewsModel(BaseModel) {
        var CustomerReviews = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.iFrameURL = this.getValue(obj.iFrameURL);
            this.hasReviews = this.getValue(obj.hasReviews);
        };

        CustomerReviews.prototype = new BaseModel();
        CustomerReviews.prototype.constructor = CustomerReviews;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CustomerReviews.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'iFrameURL', realName: 'IFrameURL' },
                { name: 'hasReviews', realName: 'HasReviews' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CustomerReviews.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CustomerReviews.prototype.getIFrameURL = function () {
            return this.iFrameURL;
        };
    
        /**
         * Setter for IFrameURL
         * 
         * @param {string|null} value 
         */
        CustomerReviews.prototype.setIFrameURL = function (value) {
            this.iFrameURL = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool|null}
         */
        CustomerReviews.prototype.getHasReviews = function () {
            return this.hasReviews;
        };
    
        /**
         * Setter for HasReviews
         * 
         * @param {bool|null} value 
         */
        CustomerReviews.prototype.setHasReviews = function (value) {
            this.hasReviews = value;
        };
    
        return CustomerReviews;
    }

}(angular));
