/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of DecimalWithUnits
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('DecimalWithUnits', ['BaseModel', DecimalWithUnitsModel]);

    function DecimalWithUnitsModel(BaseModel) {
        var DecimalWithUnits = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.units = this.getValue(obj.units);
        };

        DecimalWithUnits.prototype = new BaseModel();
        DecimalWithUnits.prototype.constructor = DecimalWithUnits;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        DecimalWithUnits.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'units', realName: 'Units' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        DecimalWithUnits.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        DecimalWithUnits.prototype.getUnits = function () {
            return this.units;
        };
    
        /**
         * Setter for Units
         * 
         * @param {string} value 
         */
        DecimalWithUnits.prototype.setUnits = function (value) {
            this.units = value;
        };
    
        return DecimalWithUnits;
    }

}(angular));
