/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of EANList
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('EANList', ['BaseModel', EANListModel]);

    function EANListModel(BaseModel) {
        var EANList = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.eANListElement = this.getValue(obj.eANListElement);
        };

        EANList.prototype = new BaseModel();
        EANList.prototype.constructor = EANList;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        EANList.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'eANListElement', realName: 'EANListElement', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        EANList.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        EANList.prototype.getEANListElement = function () {
            return this.eANListElement;
        };
    
        /**
         * Setter for EANListElement
         * 
         * @param {array|null} value 
         */
        EANList.prototype.setEANListElement = function (value) {
            this.eANListElement = value;
        };
    
        return EANList;
    }

}(angular));
