/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of EditorialReview
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('EditorialReview', ['BaseModel', EditorialReviewModel]);

    function EditorialReviewModel(BaseModel) {
        var EditorialReview = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.source = this.getValue(obj.source);
            this.content = this.getValue(obj.content);
            this.isLinkSuppressed = this.getValue(obj.isLinkSuppressed);
        };

        EditorialReview.prototype = new BaseModel();
        EditorialReview.prototype.constructor = EditorialReview;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        EditorialReview.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'source', realName: 'Source' },
                { name: 'content', realName: 'Content' },
                { name: 'isLinkSuppressed', realName: 'IsLinkSuppressed' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        EditorialReview.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        EditorialReview.prototype.getSource = function () {
            return this.source;
        };
    
        /**
         * Setter for Source
         * 
         * @param {string|null} value 
         */
        EditorialReview.prototype.setSource = function (value) {
            this.source = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        EditorialReview.prototype.getContent = function () {
            return this.content;
        };
    
        /**
         * Setter for Content
         * 
         * @param {string|null} value 
         */
        EditorialReview.prototype.setContent = function (value) {
            this.content = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool|null}
         */
        EditorialReview.prototype.getIsLinkSuppressed = function () {
            return this.isLinkSuppressed;
        };
    
        /**
         * Setter for IsLinkSuppressed
         * 
         * @param {bool|null} value 
         */
        EditorialReview.prototype.setIsLinkSuppressed = function (value) {
            this.isLinkSuppressed = value;
        };
    
        return EditorialReview;
    }

}(angular));
