/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of EditorialReviews
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('EditorialReviews', ['BaseModel', EditorialReviewsModel]);

    function EditorialReviewsModel(BaseModel) {
        var EditorialReviews = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.editorialReview = this.getValue(obj.editorialReview);
        };

        EditorialReviews.prototype = new BaseModel();
        EditorialReviews.prototype.constructor = EditorialReviews;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        EditorialReviews.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'editorialReview', realName: 'EditorialReview', array: true, type: 'EditorialReview' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        EditorialReviews.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        EditorialReviews.prototype.getEditorialReview = function () {
            return this.editorialReview;
        };
    
        /**
         * Setter for EditorialReview
         * 
         * @param {array|null} value 
         */
        EditorialReviews.prototype.setEditorialReview = function (value) {
            this.editorialReview = value;
        };
    
        return EditorialReviews;
    }

}(angular));
