/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of HTTPHeaders
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('HTTPHeaders', ['BaseModel', HTTPHeadersModel]);

    function HTTPHeadersModel(BaseModel) {
        var HTTPHeaders = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.header = this.getValue(obj.header);
        };

        HTTPHeaders.prototype = new BaseModel();
        HTTPHeaders.prototype.constructor = HTTPHeaders;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        HTTPHeaders.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'header', realName: 'Header', array: true, type: 'Header' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        HTTPHeaders.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        HTTPHeaders.prototype.getHeader = function () {
            return this.header;
        };
    
        /**
         * Setter for Header
         * 
         * @param {array|null} value 
         */
        HTTPHeaders.prototype.setHeader = function (value) {
            this.header = value;
        };
    
        return HTTPHeaders;
    }

}(angular));
