/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ImageSets
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('ImageSets', ['BaseModel', ImageSetsModel]);

    function ImageSetsModel(BaseModel) {
        var ImageSets = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.imageSet = this.getValue(obj.imageSet);
        };

        ImageSets.prototype = new BaseModel();
        ImageSets.prototype.constructor = ImageSets;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ImageSets.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'imageSet', realName: 'ImageSet', array: true, type: 'ImageSet' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ImageSets.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        ImageSets.prototype.getImageSet = function () {
            return this.imageSet;
        };
    
        /**
         * Setter for ImageSet
         * 
         * @param {array|null} value 
         */
        ImageSets.prototype.setImageSet = function (value) {
            this.imageSet = value;
        };
    
        return ImageSets;
    }

}(angular));
