/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Items
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Items', ['BaseModel', ItemsModel]);

    function ItemsModel(BaseModel) {
        var Items = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.item = this.getValue(obj.item);
        };

        Items.prototype = new BaseModel();
        Items.prototype.constructor = Items;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Items.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'item', realName: 'Item', array: true, type: 'Item' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Items.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Items.prototype.getItem = function () {
            return this.item;
        };
    
        /**
         * Setter for Item
         * 
         * @param {array|null} value 
         */
        Items.prototype.setItem = function (value) {
            this.item = value;
        };
    
        return Items;
    }

}(angular));
