/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ItemLinks
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('ItemLinks', ['BaseModel', ItemLinksModel]);

    function ItemLinksModel(BaseModel) {
        var ItemLinks = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.itemLink = this.getValue(obj.itemLink);
        };

        ItemLinks.prototype = new BaseModel();
        ItemLinks.prototype.constructor = ItemLinks;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ItemLinks.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'itemLink', realName: 'ItemLink', array: true, type: 'ItemLink' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ItemLinks.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        ItemLinks.prototype.getItemLink = function () {
            return this.itemLink;
        };
    
        /**
         * Setter for ItemLink
         * 
         * @param {array|null} value 
         */
        ItemLinks.prototype.setItemLink = function (value) {
            this.itemLink = value;
        };
    
        return ItemLinks;
    }

}(angular));
