/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Item28
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Item28', ['BaseModel', Item28Model]);

    function Item28Model(BaseModel) {
        var Item28 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.action = this.getValue(obj.action);
            this.cartItemId = this.getValue(obj.cartItemId);
            this.quantity = this.getValue(obj.quantity);
        };

        Item28.prototype = new BaseModel();
        Item28.prototype.constructor = Item28;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Item28.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'action', realName: 'Action' },
                { name: 'cartItemId', realName: 'CartItemId' },
                { name: 'quantity', realName: 'Quantity' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Item28.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ActionEnum|null}
         */
        Item28.prototype.getAction = function () {
            return this.action;
        };
    
        /**
         * Setter for Action
         * 
         * @param {ActionEnum|null} value 
         */
        Item28.prototype.setAction = function (value) {
            this.action = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Item28.prototype.getCartItemId = function () {
            return this.cartItemId;
        };
    
        /**
         * Setter for CartItemId
         * 
         * @param {string|null} value 
         */
        Item28.prototype.setCartItemId = function (value) {
            this.cartItemId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Item28.prototype.getQuantity = function () {
            return this.quantity;
        };
    
        /**
         * Setter for Quantity
         * 
         * @param {int|null} value 
         */
        Item28.prototype.setQuantity = function (value) {
            this.quantity = value;
        };
    
        return Item28;
    }

}(angular));
