/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Items117
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Items117', ['BaseModel', Items117Model]);

    function Items117Model(BaseModel) {
        var Items117 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.request = this.getValue(obj.request);
            this.correctedQuery = this.getValue(obj.correctedQuery);
            this.qid = this.getValue(obj.qid);
            this.engineQuery = this.getValue(obj.engineQuery);
            this.totalResults = this.getValue(obj.totalResults);
            this.totalPages = this.getValue(obj.totalPages);
            this.moreSearchResultsUrl = this.getValue(obj.moreSearchResultsUrl);
            this.searchResultsMap = this.getValue(obj.searchResultsMap);
            this.item = this.getValue(obj.item);
            this.searchBinSets = this.getValue(obj.searchBinSets);
        };

        Items117.prototype = new BaseModel();
        Items117.prototype.constructor = Items117;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Items117.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'request', realName: 'Request', type: 'Request' },
                { name: 'correctedQuery', realName: 'CorrectedQuery', type: 'CorrectedQuery' },
                { name: 'qid', realName: 'Qid' },
                { name: 'engineQuery', realName: 'EngineQuery' },
                { name: 'totalResults', realName: 'TotalResults' },
                { name: 'totalPages', realName: 'TotalPages' },
                { name: 'moreSearchResultsUrl', realName: 'MoreSearchResultsUrl' },
                { name: 'searchResultsMap', realName: 'SearchResultsMap', type: 'SearchResultsMap' },
                { name: 'item', realName: 'Item', array: true, type: 'Item116' },
                { name: 'searchBinSets', realName: 'SearchBinSets', type: 'SearchBinSets' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Items117.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Request|null}
         */
        Items117.prototype.getRequest = function () {
            return this.request;
        };
    
        /**
         * Setter for Request
         * 
         * @param {Request|null} value 
         */
        Items117.prototype.setRequest = function (value) {
            this.request = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {CorrectedQuery|null}
         */
        Items117.prototype.getCorrectedQuery = function () {
            return this.correctedQuery;
        };
    
        /**
         * Setter for CorrectedQuery
         * 
         * @param {CorrectedQuery|null} value 
         */
        Items117.prototype.setCorrectedQuery = function (value) {
            this.correctedQuery = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Items117.prototype.getQid = function () {
            return this.qid;
        };
    
        /**
         * Setter for Qid
         * 
         * @param {string|null} value 
         */
        Items117.prototype.setQid = function (value) {
            this.qid = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Items117.prototype.getEngineQuery = function () {
            return this.engineQuery;
        };
    
        /**
         * Setter for EngineQuery
         * 
         * @param {string|null} value 
         */
        Items117.prototype.setEngineQuery = function (value) {
            this.engineQuery = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Items117.prototype.getTotalResults = function () {
            return this.totalResults;
        };
    
        /**
         * Setter for TotalResults
         * 
         * @param {int|null} value 
         */
        Items117.prototype.setTotalResults = function (value) {
            this.totalResults = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Items117.prototype.getTotalPages = function () {
            return this.totalPages;
        };
    
        /**
         * Setter for TotalPages
         * 
         * @param {int|null} value 
         */
        Items117.prototype.setTotalPages = function (value) {
            this.totalPages = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Items117.prototype.getMoreSearchResultsUrl = function () {
            return this.moreSearchResultsUrl;
        };
    
        /**
         * Setter for MoreSearchResultsUrl
         * 
         * @param {string|null} value 
         */
        Items117.prototype.setMoreSearchResultsUrl = function (value) {
            this.moreSearchResultsUrl = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {SearchResultsMap|null}
         */
        Items117.prototype.getSearchResultsMap = function () {
            return this.searchResultsMap;
        };
    
        /**
         * Setter for SearchResultsMap
         * 
         * @param {SearchResultsMap|null} value 
         */
        Items117.prototype.setSearchResultsMap = function (value) {
            this.searchResultsMap = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Items117.prototype.getItem = function () {
            return this.item;
        };
    
        /**
         * Setter for Item
         * 
         * @param {array|null} value 
         */
        Items117.prototype.setItem = function (value) {
            this.item = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {SearchBinSets|null}
         */
        Items117.prototype.getSearchBinSets = function () {
            return this.searchBinSets;
        };
    
        /**
         * Setter for SearchBinSets
         * 
         * @param {SearchBinSets|null} value 
         */
        Items117.prototype.setSearchBinSets = function (value) {
            this.searchBinSets = value;
        };
    
        return Items117;
    }

}(angular));
