/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Item23
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Item23', ['BaseModel', Item23Model]);

    function Item23Model(BaseModel) {
        var Item23 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.aSIN = this.getValue(obj.aSIN);
            this.offerListingId = this.getValue(obj.offerListingId);
            this.quantity = this.getValue(obj.quantity);
            this.associateTag = this.getValue(obj.associateTag);
            this.listItemId = this.getValue(obj.listItemId);
            this.metaData = this.getValue(obj.metaData);
        };

        Item23.prototype = new BaseModel();
        Item23.prototype.constructor = Item23;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Item23.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'aSIN', realName: 'ASIN' },
                { name: 'offerListingId', realName: 'OfferListingId' },
                { name: 'quantity', realName: 'Quantity' },
                { name: 'associateTag', realName: 'AssociateTag' },
                { name: 'listItemId', realName: 'ListItemId' },
                { name: 'metaData', realName: 'MetaData', array: true, type: 'MetaData' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Item23.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Item23.prototype.getASIN = function () {
            return this.aSIN;
        };
    
        /**
         * Setter for ASIN
         * 
         * @param {string|null} value 
         */
        Item23.prototype.setASIN = function (value) {
            this.aSIN = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Item23.prototype.getOfferListingId = function () {
            return this.offerListingId;
        };
    
        /**
         * Setter for OfferListingId
         * 
         * @param {string|null} value 
         */
        Item23.prototype.setOfferListingId = function (value) {
            this.offerListingId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Item23.prototype.getQuantity = function () {
            return this.quantity;
        };
    
        /**
         * Setter for Quantity
         * 
         * @param {int|null} value 
         */
        Item23.prototype.setQuantity = function (value) {
            this.quantity = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Item23.prototype.getAssociateTag = function () {
            return this.associateTag;
        };
    
        /**
         * Setter for AssociateTag
         * 
         * @param {string|null} value 
         */
        Item23.prototype.setAssociateTag = function (value) {
            this.associateTag = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Item23.prototype.getListItemId = function () {
            return this.listItemId;
        };
    
        /**
         * Setter for ListItemId
         * 
         * @param {string|null} value 
         */
        Item23.prototype.setListItemId = function (value) {
            this.listItemId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Item23.prototype.getMetaData = function () {
            return this.metaData;
        };
    
        /**
         * Setter for MetaData
         * 
         * @param {array|null} value 
         */
        Item23.prototype.setMetaData = function (value) {
            this.metaData = value;
        };
    
        return Item23;
    }

}(angular));
