/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of KeyValuePair
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('KeyValuePair', ['BaseModel', KeyValuePairModel]);

    function KeyValuePairModel(BaseModel) {
        var KeyValuePair = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.key = this.getValue(obj.key);
            this.value = this.getValue(obj.value);
        };

        KeyValuePair.prototype = new BaseModel();
        KeyValuePair.prototype.constructor = KeyValuePair;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        KeyValuePair.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'key', realName: 'Key' },
                { name: 'value', realName: 'Value' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        KeyValuePair.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        KeyValuePair.prototype.getKey = function () {
            return this.key;
        };
    
        /**
         * Setter for Key
         * 
         * @param {string} value 
         */
        KeyValuePair.prototype.setKey = function (value) {
            this.key = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        KeyValuePair.prototype.getValue = function () {
            return this.value;
        };
    
        /**
         * Setter for Value
         * 
         * @param {string} value 
         */
        KeyValuePair.prototype.setValue = function (value) {
            this.value = value;
        };
    
        return KeyValuePair;
    }

}(angular));
