/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Language
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Language', ['BaseModel', LanguageModel]);

    function LanguageModel(BaseModel) {
        var Language = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.name = this.getValue(obj.name);
            this.type = this.getValue(obj.type);
            this.audioFormat = this.getValue(obj.audioFormat);
        };

        Language.prototype = new BaseModel();
        Language.prototype.constructor = Language;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Language.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'name', realName: 'Name' },
                { name: 'type', realName: 'Type' },
                { name: 'audioFormat', realName: 'AudioFormat' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Language.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Language.prototype.getName = function () {
            return this.name;
        };
    
        /**
         * Setter for Name
         * 
         * @param {string} value 
         */
        Language.prototype.setName = function (value) {
            this.name = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Language.prototype.getType = function () {
            return this.type;
        };
    
        /**
         * Setter for Type
         * 
         * @param {string|null} value 
         */
        Language.prototype.setType = function (value) {
            this.type = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Language.prototype.getAudioFormat = function () {
            return this.audioFormat;
        };
    
        /**
         * Setter for AudioFormat
         * 
         * @param {string|null} value 
         */
        Language.prototype.setAudioFormat = function (value) {
            this.audioFormat = value;
        };
    
        return Language;
    }

}(angular));
