/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Languages
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Languages', ['BaseModel', LanguagesModel]);

    function LanguagesModel(BaseModel) {
        var Languages = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.language = this.getValue(obj.language);
        };

        Languages.prototype = new BaseModel();
        Languages.prototype.constructor = Languages;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Languages.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'language', realName: 'Language', array: true, type: 'Language' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Languages.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Languages.prototype.getLanguage = function () {
            return this.language;
        };
    
        /**
         * Setter for Language
         * 
         * @param {array|null} value 
         */
        Languages.prototype.setLanguage = function (value) {
            this.language = value;
        };
    
        return Languages;
    }

}(angular));
