/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of NewReleases
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('NewReleases', ['BaseModel', NewReleasesModel]);

    function NewReleasesModel(BaseModel) {
        var NewReleases = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.newRelease = this.getValue(obj.newRelease);
        };

        NewReleases.prototype = new BaseModel();
        NewReleases.prototype.constructor = NewReleases;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        NewReleases.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'newRelease', realName: 'NewRelease', array: true, type: 'NewRelease' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        NewReleases.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        NewReleases.prototype.getNewRelease = function () {
            return this.newRelease;
        };
    
        /**
         * Setter for NewRelease
         * 
         * @param {array} value 
         */
        NewReleases.prototype.setNewRelease = function (value) {
            this.newRelease = value;
        };
    
        return NewReleases;
    }

}(angular));
