/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of NonNegativeIntegerWithUnits
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('NonNegativeIntegerWithUnits', ['BaseModel', NonNegativeIntegerWithUnitsModel]);

    function NonNegativeIntegerWithUnitsModel(BaseModel) {
        var NonNegativeIntegerWithUnits = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.units = this.getValue(obj.units);
        };

        NonNegativeIntegerWithUnits.prototype = new BaseModel();
        NonNegativeIntegerWithUnits.prototype.constructor = NonNegativeIntegerWithUnits;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        NonNegativeIntegerWithUnits.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'units', realName: 'Units' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        NonNegativeIntegerWithUnits.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        NonNegativeIntegerWithUnits.prototype.getUnits = function () {
            return this.units;
        };
    
        /**
         * Setter for Units
         * 
         * @param {string} value 
         */
        NonNegativeIntegerWithUnits.prototype.setUnits = function (value) {
            this.units = value;
        };
    
        return NonNegativeIntegerWithUnits;
    }

}(angular));
