/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Offers
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Offers', ['BaseModel', OffersModel]);

    function OffersModel(BaseModel) {
        var Offers = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.totalOffers = this.getValue(obj.totalOffers);
            this.totalOfferPages = this.getValue(obj.totalOfferPages);
            this.moreOffersUrl = this.getValue(obj.moreOffersUrl);
            this.offer = this.getValue(obj.offer);
        };

        Offers.prototype = new BaseModel();
        Offers.prototype.constructor = Offers;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Offers.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'totalOffers', realName: 'TotalOffers' },
                { name: 'totalOfferPages', realName: 'TotalOfferPages' },
                { name: 'moreOffersUrl', realName: 'MoreOffersUrl' },
                { name: 'offer', realName: 'Offer', array: true, type: 'Offer' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Offers.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Offers.prototype.getTotalOffers = function () {
            return this.totalOffers;
        };
    
        /**
         * Setter for TotalOffers
         * 
         * @param {int|null} value 
         */
        Offers.prototype.setTotalOffers = function (value) {
            this.totalOffers = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        Offers.prototype.getTotalOfferPages = function () {
            return this.totalOfferPages;
        };
    
        /**
         * Setter for TotalOfferPages
         * 
         * @param {int|null} value 
         */
        Offers.prototype.setTotalOfferPages = function (value) {
            this.totalOfferPages = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        Offers.prototype.getMoreOffersUrl = function () {
            return this.moreOffersUrl;
        };
    
        /**
         * Setter for MoreOffersUrl
         * 
         * @param {string|null} value 
         */
        Offers.prototype.setMoreOffersUrl = function (value) {
            this.moreOffersUrl = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Offers.prototype.getOffer = function () {
            return this.offer;
        };
    
        /**
         * Setter for Offer
         * 
         * @param {array|null} value 
         */
        Offers.prototype.setOffer = function (value) {
            this.offer = value;
        };
    
        return Offers;
    }

}(angular));
