/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of OfferAttributes
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('OfferAttributes', ['BaseModel', OfferAttributesModel]);

    function OfferAttributesModel(BaseModel) {
        var OfferAttributes = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.condition = this.getValue(obj.condition);
        };

        OfferAttributes.prototype = new BaseModel();
        OfferAttributes.prototype.constructor = OfferAttributes;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        OfferAttributes.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'condition', realName: 'Condition' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        OfferAttributes.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ConditionEnum|null}
         */
        OfferAttributes.prototype.getCondition = function () {
            return this.condition;
        };
    
        /**
         * Setter for Condition
         * 
         * @param {ConditionEnum|null} value 
         */
        OfferAttributes.prototype.setCondition = function (value) {
            this.condition = value;
        };
    
        return OfferAttributes;
    }

}(angular));
