/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of OtherCategoriesSimilarProducts
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('OtherCategoriesSimilarProducts', ['BaseModel', OtherCategoriesSimilarProductsModel]);

    function OtherCategoriesSimilarProductsModel(BaseModel) {
        var OtherCategoriesSimilarProducts = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.otherCategoriesSimilarProduct = this.getValue(obj.otherCategoriesSimilarProduct);
        };

        OtherCategoriesSimilarProducts.prototype = new BaseModel();
        OtherCategoriesSimilarProducts.prototype.constructor = OtherCategoriesSimilarProducts;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        OtherCategoriesSimilarProducts.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                {
                    name: 'otherCategoriesSimilarProduct',
                    realName: 'OtherCategoriesSimilarProduct',
                    array: true,
                    type: 'OtherCategoriesSimilarProduct',
                }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        OtherCategoriesSimilarProducts.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        OtherCategoriesSimilarProducts.prototype.getOtherCategoriesSimilarProduct = function () {
            return this.otherCategoriesSimilarProduct;
        };
    
        /**
         * Setter for OtherCategoriesSimilarProduct
         * 
         * @param {array} value 
         */
        OtherCategoriesSimilarProducts.prototype.setOtherCategoriesSimilarProduct = function (value) {
            this.otherCategoriesSimilarProduct = value;
        };
    
        return OtherCategoriesSimilarProducts;
    }

}(angular));
