/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of PackageDimensions
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('PackageDimensions', ['BaseModel', PackageDimensionsModel]);

    function PackageDimensionsModel(BaseModel) {
        var PackageDimensions = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.height = this.getValue(obj.height);
            this.length = this.getValue(obj.length);
            this.weight = this.getValue(obj.weight);
            this.width = this.getValue(obj.width);
        };

        PackageDimensions.prototype = new BaseModel();
        PackageDimensions.prototype.constructor = PackageDimensions;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        PackageDimensions.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'height', realName: 'Height', type: 'DecimalWithUnits' },
                { name: 'length', realName: 'Length', type: 'DecimalWithUnits' },
                { name: 'weight', realName: 'Weight', type: 'DecimalWithUnits' },
                { name: 'width', realName: 'Width', type: 'DecimalWithUnits' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        PackageDimensions.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {DecimalWithUnits|null}
         */
        PackageDimensions.prototype.getHeight = function () {
            return this.height;
        };
    
        /**
         * Setter for Height
         * 
         * @param {DecimalWithUnits|null} value 
         */
        PackageDimensions.prototype.setHeight = function (value) {
            this.height = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {DecimalWithUnits|null}
         */
        PackageDimensions.prototype.getLength = function () {
            return this.length;
        };
    
        /**
         * Setter for Length
         * 
         * @param {DecimalWithUnits|null} value 
         */
        PackageDimensions.prototype.setLength = function (value) {
            this.length = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {DecimalWithUnits|null}
         */
        PackageDimensions.prototype.getWeight = function () {
            return this.weight;
        };
    
        /**
         * Setter for Weight
         * 
         * @param {DecimalWithUnits|null} value 
         */
        PackageDimensions.prototype.setWeight = function (value) {
            this.weight = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {DecimalWithUnits|null}
         */
        PackageDimensions.prototype.getWidth = function () {
            return this.width;
        };
    
        /**
         * Setter for Width
         * 
         * @param {DecimalWithUnits|null} value 
         */
        PackageDimensions.prototype.setWidth = function (value) {
            this.width = value;
        };
    
        return PackageDimensions;
    }

}(angular));
