/**
  * AWSECommerceServiceLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('AWSECommerceServiceLib')
    .factory('PositiveIntegerOrAllEnum', [PositiveIntegerOrAllEnumModel]);

    function PositiveIntegerOrAllEnumModel() {
        return {
            //TODO: Write general description for this element
            ALL: 'All'
        };
    }

}(angular));
