/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Promotions
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Promotions', ['BaseModel', PromotionsModel]);

    function PromotionsModel(BaseModel) {
        var Promotions = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.promotion = this.getValue(obj.promotion);
        };

        Promotions.prototype = new BaseModel();
        Promotions.prototype.constructor = Promotions;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Promotions.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'promotion', realName: 'Promotion', array: true, type: 'Promotion' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Promotions.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Promotions.prototype.getPromotion = function () {
            return this.promotion;
        };
    
        /**
         * Setter for Promotion
         * 
         * @param {array|null} value 
         */
        Promotions.prototype.setPromotion = function (value) {
            this.promotion = value;
        };
    
        return Promotions;
    }

}(angular));
