/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Promotion
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Promotion', ['BaseModel', PromotionModel]);

    function PromotionModel(BaseModel) {
        var Promotion = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.summary = this.getValue(obj.summary);
        };

        Promotion.prototype = new BaseModel();
        Promotion.prototype.constructor = Promotion;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Promotion.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'summary', realName: 'Summary', type: 'Summary' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Promotion.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Summary|null}
         */
        Promotion.prototype.getSummary = function () {
            return this.summary;
        };
    
        /**
         * Setter for Summary
         * 
         * @param {Summary|null} value 
         */
        Promotion.prototype.setSummary = function (value) {
            this.summary = value;
        };
    
        return Promotion;
    }

}(angular));
