/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Properties
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Properties', ['BaseModel', PropertiesModel]);

    function PropertiesModel(BaseModel) {
        var Properties = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.property = this.getValue(obj.property);
        };

        Properties.prototype = new BaseModel();
        Properties.prototype.constructor = Properties;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Properties.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'property', realName: 'Property', array: true, type: 'Property' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Properties.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        Properties.prototype.getProperty = function () {
            return this.property;
        };
    
        /**
         * Setter for Property
         * 
         * @param {array} value 
         */
        Properties.prototype.setProperty = function (value) {
            this.property = value;
        };
    
        return Properties;
    }

}(angular));
