/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RelatedItems
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('RelatedItems', ['BaseModel', RelatedItemsModel]);

    function RelatedItemsModel(BaseModel) {
        var RelatedItems = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.relationship = this.getValue(obj.relationship);
            this.relationshipType = this.getValue(obj.relationshipType);
            this.relatedItemCount = this.getValue(obj.relatedItemCount);
            this.relatedItemPageCount = this.getValue(obj.relatedItemPageCount);
            this.relatedItemPage = this.getValue(obj.relatedItemPage);
            this.relatedItem = this.getValue(obj.relatedItem);
        };

        RelatedItems.prototype = new BaseModel();
        RelatedItems.prototype.constructor = RelatedItems;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        RelatedItems.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'relationship', realName: 'Relationship' },
                { name: 'relationshipType', realName: 'RelationshipType' },
                { name: 'relatedItemCount', realName: 'RelatedItemCount' },
                { name: 'relatedItemPageCount', realName: 'RelatedItemPageCount' },
                { name: 'relatedItemPage', realName: 'RelatedItemPage' },
                { name: 'relatedItem', realName: 'RelatedItem', array: true, type: 'RelatedItem' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        RelatedItems.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {RelationshipEnum|null}
         */
        RelatedItems.prototype.getRelationship = function () {
            return this.relationship;
        };
    
        /**
         * Setter for Relationship
         * 
         * @param {RelationshipEnum|null} value 
         */
        RelatedItems.prototype.setRelationship = function (value) {
            this.relationship = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        RelatedItems.prototype.getRelationshipType = function () {
            return this.relationshipType;
        };
    
        /**
         * Setter for RelationshipType
         * 
         * @param {string|null} value 
         */
        RelatedItems.prototype.setRelationshipType = function (value) {
            this.relationshipType = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        RelatedItems.prototype.getRelatedItemCount = function () {
            return this.relatedItemCount;
        };
    
        /**
         * Setter for RelatedItemCount
         * 
         * @param {int|null} value 
         */
        RelatedItems.prototype.setRelatedItemCount = function (value) {
            this.relatedItemCount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        RelatedItems.prototype.getRelatedItemPageCount = function () {
            return this.relatedItemPageCount;
        };
    
        /**
         * Setter for RelatedItemPageCount
         * 
         * @param {int|null} value 
         */
        RelatedItems.prototype.setRelatedItemPageCount = function (value) {
            this.relatedItemPageCount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        RelatedItems.prototype.getRelatedItemPage = function () {
            return this.relatedItemPage;
        };
    
        /**
         * Setter for RelatedItemPage
         * 
         * @param {int|null} value 
         */
        RelatedItems.prototype.setRelatedItemPage = function (value) {
            this.relatedItemPage = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        RelatedItems.prototype.getRelatedItem = function () {
            return this.relatedItem;
        };
    
        /**
         * Setter for RelatedItem
         * 
         * @param {array|null} value 
         */
        RelatedItems.prototype.setRelatedItem = function (value) {
            this.relatedItem = value;
        };
    
        return RelatedItems;
    }

}(angular));
