/**
  * AWSECommerceServiceLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('AWSECommerceServiceLib')
    .factory('RelationshipEnum', [RelationshipEnumModel]);

    function RelationshipEnumModel() {
        return {
            //TODO: Write general description for this element
            PARENTS: 'Parents',
    
            //TODO: Write general description for this element
            CHILDREN: 'Children'
        };
    }

}(angular));
