/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RentalOffer
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('RentalOffer', ['BaseModel', RentalOfferModel]);

    function RentalOfferModel(BaseModel) {
        var RentalOffer = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.merchant = this.getValue(obj.merchant);
            this.rentalListing = this.getValue(obj.rentalListing);
        };

        RentalOffer.prototype = new BaseModel();
        RentalOffer.prototype.constructor = RentalOffer;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        RentalOffer.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'merchant', realName: 'Merchant', type: 'Merchant' },
                { name: 'rentalListing', realName: 'RentalListing', array: true, type: 'RentalListing' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        RentalOffer.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Merchant|null}
         */
        RentalOffer.prototype.getMerchant = function () {
            return this.merchant;
        };
    
        /**
         * Setter for Merchant
         * 
         * @param {Merchant|null} value 
         */
        RentalOffer.prototype.setMerchant = function (value) {
            this.merchant = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        RentalOffer.prototype.getRentalListing = function () {
            return this.rentalListing;
        };
    
        /**
         * Setter for RentalListing
         * 
         * @param {array|null} value 
         */
        RentalOffer.prototype.setRentalListing = function (value) {
            this.rentalListing = value;
        };
    
        return RentalOffer;
    }

}(angular));
