/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RentalOffers
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('RentalOffers', ['BaseModel', RentalOffersModel]);

    function RentalOffersModel(BaseModel) {
        var RentalOffers = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.rentalOffer = this.getValue(obj.rentalOffer);
        };

        RentalOffers.prototype = new BaseModel();
        RentalOffers.prototype.constructor = RentalOffers;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        RentalOffers.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'rentalOffer', realName: 'RentalOffer', array: true, type: 'RentalOffer' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        RentalOffers.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        RentalOffers.prototype.getRentalOffer = function () {
            return this.rentalOffer;
        };
    
        /**
         * Setter for RentalOffer
         * 
         * @param {array|null} value 
         */
        RentalOffers.prototype.setRentalOffer = function (value) {
            this.rentalOffer = value;
        };
    
        return RentalOffers;
    }

}(angular));
