/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SavedForLaterItems
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SavedForLaterItems', ['BaseModel', SavedForLaterItemsModel]);

    function SavedForLaterItemsModel(BaseModel) {
        var SavedForLaterItems = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.savedForLaterItem = this.getValue(obj.savedForLaterItem);
            this.subTotal = this.getValue(obj.subTotal);
        };

        SavedForLaterItems.prototype = new BaseModel();
        SavedForLaterItems.prototype.constructor = SavedForLaterItems;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SavedForLaterItems.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'savedForLaterItem', realName: 'SavedForLaterItem', array: true, type: 'CartItem' },
                { name: 'subTotal', realName: 'SubTotal', type: 'Price' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SavedForLaterItems.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        SavedForLaterItems.prototype.getSavedForLaterItem = function () {
            return this.savedForLaterItem;
        };
    
        /**
         * Setter for SavedForLaterItem
         * 
         * @param {array} value 
         */
        SavedForLaterItems.prototype.setSavedForLaterItem = function (value) {
            this.savedForLaterItem = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Price|null}
         */
        SavedForLaterItems.prototype.getSubTotal = function () {
            return this.subTotal;
        };
    
        /**
         * Setter for SubTotal
         * 
         * @param {Price|null} value 
         */
        SavedForLaterItems.prototype.setSubTotal = function (value) {
            this.subTotal = value;
        };
    
        return SavedForLaterItems;
    }

}(angular));
