/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SearchResultsMap
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SearchResultsMap', ['BaseModel', SearchResultsMapModel]);

    function SearchResultsMapModel(BaseModel) {
        var SearchResultsMap = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.searchIndex = this.getValue(obj.searchIndex);
        };

        SearchResultsMap.prototype = new BaseModel();
        SearchResultsMap.prototype.constructor = SearchResultsMap;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SearchResultsMap.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'searchIndex', realName: 'SearchIndex', array: true, type: 'SearchIndex' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SearchResultsMap.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        SearchResultsMap.prototype.getSearchIndex = function () {
            return this.searchIndex;
        };
    
        /**
         * Setter for SearchIndex
         * 
         * @param {array} value 
         */
        SearchResultsMap.prototype.setSearchIndex = function (value) {
            this.searchIndex = value;
        };
    
        return SearchResultsMap;
    }

}(angular));
