/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SearchBinSets
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SearchBinSets', ['BaseModel', SearchBinSetsModel]);

    function SearchBinSetsModel(BaseModel) {
        var SearchBinSets = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.searchBinSet = this.getValue(obj.searchBinSet);
        };

        SearchBinSets.prototype = new BaseModel();
        SearchBinSets.prototype.constructor = SearchBinSets;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SearchBinSets.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'searchBinSet', realName: 'SearchBinSet', array: true, type: 'SearchBinSet' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SearchBinSets.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        SearchBinSets.prototype.getSearchBinSet = function () {
            return this.searchBinSet;
        };
    
        /**
         * Setter for SearchBinSet
         * 
         * @param {array|null} value 
         */
        SearchBinSets.prototype.setSearchBinSet = function (value) {
            this.searchBinSet = value;
        };
    
        return SearchBinSets;
    }

}(angular));
