/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SearchBinSet
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SearchBinSet', ['BaseModel', SearchBinSetModel]);

    function SearchBinSetModel(BaseModel) {
        var SearchBinSet = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.narrowBy = this.getValue(obj.narrowBy);
            this.bin = this.getValue(obj.bin);
        };

        SearchBinSet.prototype = new BaseModel();
        SearchBinSet.prototype.constructor = SearchBinSet;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SearchBinSet.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'narrowBy', realName: 'NarrowBy' },
                { name: 'bin', realName: 'Bin', array: true, type: 'Bin' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SearchBinSet.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SearchBinSet.prototype.getNarrowBy = function () {
            return this.narrowBy;
        };
    
        /**
         * Setter for NarrowBy
         * 
         * @param {string} value 
         */
        SearchBinSet.prototype.setNarrowBy = function (value) {
            this.narrowBy = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        SearchBinSet.prototype.getBin = function () {
            return this.bin;
        };
    
        /**
         * Setter for Bin
         * 
         * @param {array|null} value 
         */
        SearchBinSet.prototype.setBin = function (value) {
            this.bin = value;
        };
    
        return SearchBinSet;
    }

}(angular));
