/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SimilarViewedProducts
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SimilarViewedProducts', ['BaseModel', SimilarViewedProductsModel]);

    function SimilarViewedProductsModel(BaseModel) {
        var SimilarViewedProducts = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.similarViewedProduct = this.getValue(obj.similarViewedProduct);
        };

        SimilarViewedProducts.prototype = new BaseModel();
        SimilarViewedProducts.prototype.constructor = SimilarViewedProducts;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SimilarViewedProducts.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                {
                    name: 'similarViewedProduct',
                    realName: 'SimilarViewedProduct',
                    array: true,
                    type: 'SimilarViewedProduct',
                }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SimilarViewedProducts.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        SimilarViewedProducts.prototype.getSimilarViewedProduct = function () {
            return this.similarViewedProduct;
        };
    
        /**
         * Setter for SimilarViewedProduct
         * 
         * @param {array} value 
         */
        SimilarViewedProducts.prototype.setSimilarViewedProduct = function (value) {
            this.similarViewedProduct = value;
        };
    
        return SimilarViewedProducts;
    }

}(angular));
