/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SimilarProducts
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SimilarProducts', ['BaseModel', SimilarProductsModel]);

    function SimilarProductsModel(BaseModel) {
        var SimilarProducts = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.similarProduct = this.getValue(obj.similarProduct);
        };

        SimilarProducts.prototype = new BaseModel();
        SimilarProducts.prototype.constructor = SimilarProducts;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SimilarProducts.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'similarProduct', realName: 'SimilarProduct', array: true, type: 'SimilarProduct' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SimilarProducts.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        SimilarProducts.prototype.getSimilarProduct = function () {
            return this.similarProduct;
        };
    
        /**
         * Setter for SimilarProduct
         * 
         * @param {array} value 
         */
        SimilarProducts.prototype.setSimilarProduct = function (value) {
            this.similarProduct = value;
        };
    
        return SimilarProducts;
    }

}(angular));
