/**
  * AWSECommerceServiceLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('AWSECommerceServiceLib')
    .factory('SimilarityTypeEnum', [SimilarityTypeEnumModel]);

    function SimilarityTypeEnumModel() {
        return {
            //TODO: Write general description for this element
            INTERSECTION: 'Intersection',
    
            //TODO: Write general description for this element
            RANDOM: 'Random'
        };
    }

}(angular));
