/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SimilarityLookupRequest
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SimilarityLookupRequest', ['BaseModel', SimilarityLookupRequestModel]);

    function SimilarityLookupRequestModel(BaseModel) {
        var SimilarityLookupRequest = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.condition = this.getValue(obj.condition);
            this.itemId = this.getValue(obj.itemId);
            this.merchantId = this.getValue(obj.merchantId);
            this.responseGroup = this.getValue(obj.responseGroup);
            this.similarityType = this.getValue(obj.similarityType);
        };

        SimilarityLookupRequest.prototype = new BaseModel();
        SimilarityLookupRequest.prototype.constructor = SimilarityLookupRequest;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SimilarityLookupRequest.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'condition', realName: 'Condition' },
                { name: 'itemId', realName: 'ItemId', array: true },
                { name: 'merchantId', realName: 'MerchantId' },
                { name: 'responseGroup', realName: 'ResponseGroup', array: true },
                { name: 'similarityType', realName: 'SimilarityType' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SimilarityLookupRequest.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ConditionEnum|null}
         */
        SimilarityLookupRequest.prototype.getCondition = function () {
            return this.condition;
        };
    
        /**
         * Setter for Condition
         * 
         * @param {ConditionEnum|null} value 
         */
        SimilarityLookupRequest.prototype.setCondition = function (value) {
            this.condition = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        SimilarityLookupRequest.prototype.getItemId = function () {
            return this.itemId;
        };
    
        /**
         * Setter for ItemId
         * 
         * @param {array|null} value 
         */
        SimilarityLookupRequest.prototype.setItemId = function (value) {
            this.itemId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        SimilarityLookupRequest.prototype.getMerchantId = function () {
            return this.merchantId;
        };
    
        /**
         * Setter for MerchantId
         * 
         * @param {string|null} value 
         */
        SimilarityLookupRequest.prototype.setMerchantId = function (value) {
            this.merchantId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        SimilarityLookupRequest.prototype.getResponseGroup = function () {
            return this.responseGroup;
        };
    
        /**
         * Setter for ResponseGroup
         * 
         * @param {array|null} value 
         */
        SimilarityLookupRequest.prototype.setResponseGroup = function (value) {
            this.responseGroup = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {SimilarityTypeEnum|null}
         */
        SimilarityLookupRequest.prototype.getSimilarityType = function () {
            return this.similarityType;
        };
    
        /**
         * Setter for SimilarityType
         * 
         * @param {SimilarityTypeEnum|null} value 
         */
        SimilarityLookupRequest.prototype.setSimilarityType = function (value) {
            this.similarityType = value;
        };
    
        return SimilarityLookupRequest;
    }

}(angular));
