/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SimilarityLookupRequestMsg
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('SimilarityLookupRequestMsg', ['BaseModel', SimilarityLookupRequestMsgModel]);

    function SimilarityLookupRequestMsgModel(BaseModel) {
        var SimilarityLookupRequestMsg = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.body = this.getValue(obj.body);
        };

        SimilarityLookupRequestMsg.prototype = new BaseModel();
        SimilarityLookupRequestMsg.prototype.constructor = SimilarityLookupRequestMsg;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SimilarityLookupRequestMsg.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'body', realName: 'body', type: 'SimilarityLookup' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SimilarityLookupRequestMsg.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {SimilarityLookup}
         */
        SimilarityLookupRequestMsg.prototype.getBody = function () {
            return this.body;
        };
    
        /**
         * Setter for Body
         * 
         * @param {SimilarityLookup} value 
         */
        SimilarityLookupRequestMsg.prototype.setBody = function (value) {
            this.body = value;
        };
    
        return SimilarityLookupRequestMsg;
    }

}(angular));
