/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Subjects
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Subjects', ['BaseModel', SubjectsModel]);

    function SubjectsModel(BaseModel) {
        var Subjects = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.subject = this.getValue(obj.subject);
        };

        Subjects.prototype = new BaseModel();
        Subjects.prototype.constructor = Subjects;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Subjects.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'subject', realName: 'Subject', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Subjects.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        Subjects.prototype.getSubject = function () {
            return this.subject;
        };
    
        /**
         * Setter for Subject
         * 
         * @param {array|null} value 
         */
        Subjects.prototype.setSubject = function (value) {
            this.subject = value;
        };
    
        return Subjects;
    }

}(angular));
