/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TopItemSet
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('TopItemSet', ['BaseModel', TopItemSetModel]);

    function TopItemSetModel(BaseModel) {
        var TopItemSet = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.topItem = this.getValue(obj.topItem);
            this.type = this.getValue(obj.type);
        };

        TopItemSet.prototype = new BaseModel();
        TopItemSet.prototype.constructor = TopItemSet;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TopItemSet.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'topItem', realName: 'TopItem', array: true, type: 'TopItem' },
                { name: 'type', realName: 'Type' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TopItemSet.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        TopItemSet.prototype.getTopItem = function () {
            return this.topItem;
        };
    
        /**
         * Setter for TopItem
         * 
         * @param {array} value 
         */
        TopItemSet.prototype.setTopItem = function (value) {
            this.topItem = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        TopItemSet.prototype.getType = function () {
            return this.type;
        };
    
        /**
         * Setter for Type
         * 
         * @param {string|null} value 
         */
        TopItemSet.prototype.setType = function (value) {
            this.type = value;
        };
    
        return TopItemSet;
    }

}(angular));
