/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TopSellers
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('TopSellers', ['BaseModel', TopSellersModel]);

    function TopSellersModel(BaseModel) {
        var TopSellers = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.topSeller = this.getValue(obj.topSeller);
        };

        TopSellers.prototype = new BaseModel();
        TopSellers.prototype.constructor = TopSellers;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TopSellers.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'topSeller', realName: 'TopSeller', array: true, type: 'TopSeller' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TopSellers.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        TopSellers.prototype.getTopSeller = function () {
            return this.topSeller;
        };
    
        /**
         * Setter for TopSeller
         * 
         * @param {array} value 
         */
        TopSellers.prototype.setTopSeller = function (value) {
            this.topSeller = value;
        };
    
        return TopSellers;
    }

}(angular));
