/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Tracks
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Tracks', ['BaseModel', TracksModel]);

    function TracksModel(BaseModel) {
        var Tracks = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.disc = this.getValue(obj.disc);
        };

        Tracks.prototype = new BaseModel();
        Tracks.prototype.constructor = Tracks;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Tracks.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'disc', realName: 'Disc', array: true, type: 'Disc' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Tracks.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        Tracks.prototype.getDisc = function () {
            return this.disc;
        };
    
        /**
         * Setter for Disc
         * 
         * @param {array} value 
         */
        Tracks.prototype.setDisc = function (value) {
            this.disc = value;
        };
    
        return Tracks;
    }

}(angular));
