/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Track
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('Track', ['BaseModel', TrackModel]);

    function TrackModel(BaseModel) {
        var Track = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.number = this.getValue(obj.number);
        };

        Track.prototype = new BaseModel();
        Track.prototype.constructor = Track;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Track.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'number', realName: 'Number' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Track.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        Track.prototype.getNumber = function () {
            return this.number;
        };
    
        /**
         * Setter for Number
         * 
         * @param {int} value 
         */
        Track.prototype.setNumber = function (value) {
            this.number = value;
        };
    
        return Track;
    }

}(angular));
