/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of VariationAttributes
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('VariationAttributes', ['BaseModel', VariationAttributesModel]);

    function VariationAttributesModel(BaseModel) {
        var VariationAttributes = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.variationAttribute = this.getValue(obj.variationAttribute);
        };

        VariationAttributes.prototype = new BaseModel();
        VariationAttributes.prototype.constructor = VariationAttributes;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        VariationAttributes.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'variationAttribute', realName: 'VariationAttribute', array: true, type: 'VariationAttribute' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        VariationAttributes.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        VariationAttributes.prototype.getVariationAttribute = function () {
            return this.variationAttribute;
        };
    
        /**
         * Setter for VariationAttribute
         * 
         * @param {array|null} value 
         */
        VariationAttributes.prototype.setVariationAttribute = function (value) {
            this.variationAttribute = value;
        };
    
        return VariationAttributes;
    }

}(angular));
